### ISSUE TITLE
Question about the merge_bn.py

### ISSUE THREAD

**Issue by ailihong** [chuanqi305/MobileNetv2-SSDLite#14]
When I use v1's merge_bn.py to merge v2's model and report the following error, does anyone know how to solve it? Thank you.

I0531 13:10:13.336994   270 net.cpp:283] Network initialization done.
Traceback (most recent call last):
  File "merge_bn.py", line 63, in <module>
    merge_bn(net, net_deploy)
  File "merge_bn.py", line 57, in merge_bn
    nob.params[key][1].data[...] = bias
IndexError: Index out of range

**Comment by ailihong** [comment]
I fix it. the param (bias_term) of my conv layer is false ...

if len(nob.params[key])==2:#bias_term is not false
    nob.params[key][1].data[...] = bias
