### ISSUE TITLE
Error when creating deploy.caffemodel using load_caffe_weights.py, ValueError: cannot reshape array of size 157248 into shape (6,576,1,1)

### ISSUE THREAD

**Issue by chinthysl** [chuanqi305/MobileNetv2-SSDLite#24]
dump_tensorflow_weights.py works well with the downloaded ssdlite_mobilenet_v2_coco_2018_05_09 model. But stuck at converting it to caffe model using the load_caffe_weights.py script

Traceback (most recent call last):
  File "load_caffe_weights.py", line 82, in <module>
    load_data(net_deploy)
  File "load_caffe_weights.py", line 74, in load_data
    net.params[key][0].data[...] = load_weights(prefix + '_weights.dat', net.params[key][0].data.shape)
  File "load_caffe_weights.py", line 17, in load_weights
    weights = np.fromfile(path, dtype=np.float32).reshape(shape)
ValueError: cannot reshape array of size 157248 into shape (6,576,1,1)

**Comment by baiboat** [comment]
did you fixed this error,i got the same error

**Comment by tringn** [comment]
I got same Error. Did you fix it?

**Comment by chinthysl** [comment]
@baiboat  @tringn please look at the #22 
I continued my work with MobileNetV1. Stopped at this error. Ha vent tried yet with solutions in #22

**Comment by manoj652** [comment]
File "dump_tensorflow_weights.py", line 77, in <module>
    tmp = caffe_weights.reshape(boxes, -1).copy()
ValueError: cannot reshape array of size 31104 into shape (0,newaxis)
