### ISSUE TITLE
dump_tensorflow_weights.py with error

### ISSUE THREAD

**Issue by he-chen** [chuanqi305/MobileNetv2-SSDLite#28]
i run the following command :python3 dump_tensorflow_weights.py 
and get this error:
Traceback (most recent call last):
  File "dump_tensorflow_weights.py", line 95, in <module>
    tmp = caffe_weights.reshape(boxes, -1).copy()
TypeError: 'float' object cannot be interpreted as an integer

i fix it by change the code at line 71 

if output_name.find('BoxEncodingPredictor') != -1:
                     boxes = caffe_weights.shape[0] / 4
                 elif output_name.find('ClassPredictor') != -1:
                     boxes = caffe_weights.shape[0] / 91

to 

if output_name.find('BoxEncodingPredictor') != -1:
                     boxes = caffe_weights.shape[0] // 4
                 elif output_name.find('ClassPredictor') != -1:
                     boxes = caffe_weights.shape[0] // 91

and i wonder if  it is ok  or not ?

**Comment by zhanghanbin3159** [comment]
it ok!
this script is write by python2, if you use python3,should change '/' to '//'

**Comment by manoj652** [comment]
File "dump_tensorflow_weights.py", line 77, in <module>
    tmp = caffe_weights.reshape(boxes, -1).copy()
ValueError: cannot reshape array of size 31104 into shape (0,newaxis)

**Comment by chuanqi305** [comment]
@he-chen Thank you very much, I have merged your code to my project.
